label: clingy flow
steps:
- label: start
  description: starting clingy flow
  command: echo -e "\033[34mStarting\033[0m"
- label: build clingy
  description: building clingy with Makefile target
  command: make build
- label: clingy init
  description: displaying printout of only calling clingy
  command: build/clingy -d
- label: clingy help
  description: display help text for clingy
  command: build/clingy --help -d
- label: finish
  description: finished clingy flow
  command: echo -e "\033[92mComplete\033[0m"