markdown_extensions:
  - md_in_html
  - meta
  - pymdownx.critic
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: true
plugins:
  - search
  - tags
repo_url: https://github.com/madhuravius/clingy
site_name: clingy
theme:
  features:
    - toc.integrate
  shortcuts: Defines
  icon:
    repo: fontawesome/brands/git-alt
  name: material
  palette:
    primary: deep purple