name: Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'
      - run: go install gotest.tools/gotestsum@latest
      - run: gotestsum --format testname -- -coverprofile=cover.out ./...
        env:
          WINDOWID: 0000001